# Generated by Django 5.2.1 on 2025-10-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(choices=[('Land(L001)', 'Land(L001)'), ('Building(B001)', 'Building(B001)'), ('Furniture Fixtures(FF001)', 'Furniture Fixtures(FF001)'), ('Office Equipment(OE001)', 'Office Equipment(OE001)'), ('Computers(C001)', 'Computers(C001)'), ('Plant Machinery(PM001', 'Plant Machinery(PM001'), ('Vehicles(V001)', 'Vehicles(V001)'), ('Intangibles(I001)', 'Intangibles(I001)')], on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(choices=[('HRD', 'HRD'), ('Administration', 'Administration'), ('Placements', 'Placements'), ('Operations', 'Operations'), ('Students Success Department', 'Students Success Department'), ('Admissions', 'Admissions'), ('Accounts & Finance', 'Accounts & Finance'), ('Academics', 'Academics'), ('IT', 'IT'), ('Digital Marketing', 'Digital Marketing'), ('Students Success Department', 'Students Success Department'), ('Certificate', 'Certificate'), ('Sales', 'Sales')], on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(choices=[('PALARIVATTOM', 'PALARIVATTOM'), ('VYTTILA', 'VYTTILA')], on_delete=django.db.models.deletion.CASCADE, to='myapp.location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sub_category',
            field=models.ForeignKey(choices=[('Freehold Land', 'Freehold Land'), ('Leasehold Land', 'Leasehold Land'), ('Agricultural Land', 'Agricultural Land'), ('Industrial Land', 'Industrial Land'), ('Commercial Plot', 'Commercial Plot'), ('Residential Plot', 'Residential Plot'), ('Development Site / Vacant Land', 'Development Site / Vacant Land'), ('Land with Building', 'Land with Building'), ('Office Building', 'Office Building'), ('Factory Building', 'Factory Building'), ('Warehouse / Godown', 'Warehouse / Godown'), ('Residential Building', 'Residential Building'), ('Leasehold Improvements', 'Leasehold Improvements'), ('Electrical Installations', 'Electrical Installations'), ('Temporary Structure', 'Temporary Structure'), ('Office Chair', 'Office Chair')], on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory'),
        ),
    ]
