# Generated by Django 5.2.7 on 2025-11-14 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_assetcreate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='assetcreate',
            name='assetname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='assetcreate',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='assetcreate',
            name='make',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='assetcreate',
            name='remarks',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='myapp.asset'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'user')], max_length=10),
        ),
    ]
