# Generated by Django 5.2.1 on 2025-10-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_asset_category_alter_asset_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='department',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created_by',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='make_model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='warranty_expiry',
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='title',
            field=models.CharField(default='Untitled Asset', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
