# Generated by Django 5.2.1 on 2025-10-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_asset_category_remove_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
