# Generated by Django 5.2.7 on 2025-10-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_asset_category_remove_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='myapp.asset')),
            ],
        ),
    ]
