# Generated by Django 5.2.7 on 2025-11-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_asset_title_alter_assetcreate_assetname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
