# Generated by Django 5.2.7 on 2025-11-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_asset_title_alter_department_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcreate',
            name='assetname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=12),
        ),
    ]
