# Generated by Django 5.2.7 on 2025-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_assetcreate_assetname_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcreate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='asset_files/'),
        ),
        migrations.AlterField(
            model_name='assetcreate',
            name='assetname',
            field=models.CharField(max_length=30),
        ),
    ]
