# Generated by Django 5.2.1 on 2025-10-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_asset_title'),
        ('myapp', '0005_subcategory'),
    ]

    operations = [
    ]
