# Generated by Django 5.2.1 on 2025-12-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_assetcreate_file_alter_assetcreate_assetname'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcreate',
            name='asset_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetcreate',
            name='assetname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
