# Generated by Django 5.2.7 on 2025-12-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_assetcreate_file_alter_assetcreate_assetname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcreate',
            name='assetname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
