# Generated by Django 5.2.1 on 2025-10-22 04:21
# Generated by Django 5.2.7 on 2025-10-22 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_location'),
        ('myapp', '0007_user'),
    ]

    operations = [
    ]
